/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Table structure for table `rsvp_****_Admin`
--

--
-- Table structure for table `rsvp_****_Admin`
--

CREATE TABLE IF NOT EXISTS `rsvp_****_Admin` (
  -- `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SETTING` varchar(256) COLLATE utf8_unicode_ci NOT NULL,
  `VALUE` varchar(256) COLLATE utf8_unicode_ci NOT NULL,
  UNIQUE KEY `SETTING` (`SETTING`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=143 ;

INSERT INTO `rsvp_****_Adimn` (`SETTING`, `VALUE`)
VALUES (`RSVP_TYPE`, `Open`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
